import type { FurnitureCategoryId } from "@/lib/furniture-categories";

export type FurnitureCatalogItem = {
  category: FurnitureCategoryId;
  furnitureName: string;
  heightCm: number;
  id: string;
  lengthCm: number;
  rooms: string[];
  standardRooms: string[];
  widthCm: number;
};

export const furnitureCatalog: FurnitureCatalogItem[] = [
  {
    id: "bed-90x200",
    category: "bed",
    furnitureName: "Bett 90x200",
    lengthCm: 200,
    widthCm: 90,
    heightCm: 60,
    standardRooms: ["Schlafzimmer", "Gästezimmer", "Kinderzimmer"],
    rooms: ["Schlafzimmer", "Gästezimmer", "Kinderzimmer"],
  },
  {
    id: "wardrobe",
    category: "cabinet",
    furnitureName: "Kleiderschrank",
    lengthCm: 180,
    widthCm: 60,
    heightCm: 220,
    standardRooms: ["Schlafzimmer", "Gästezimmer"],
    rooms: ["Schlafzimmer", "Gästezimmer"],
  },
  {
    id: "nightstand",
    category: "table",
    furnitureName: "Nachttisch",
    lengthCm: 50,
    widthCm: 40,
    heightCm: 55,
    standardRooms: ["Schlafzimmer", "Gästezimmer"],
    rooms: ["Schlafzimmer", "Gästezimmer"],
  },
  {
    id: "dresser",
    category: "dresser",
    furnitureName: "Kommode",
    lengthCm: 100,
    widthCm: 45,
    heightCm: 90,
    standardRooms: ["Schlafzimmer", "Wohnzimmer", "Kinderzimmer"],
    rooms: ["Schlafzimmer", "Wohnzimmer", "Kinderzimmer"],
  },
  {
    id: "sofa-3-seater",
    category: "seating",
    furnitureName: "Sofa 3-Sitzer",
    lengthCm: 220,
    widthCm: 95,
    heightCm: 85,
    standardRooms: ["Wohnzimmer"],
    rooms: ["Wohnzimmer"],
  },
  {
    id: "coffee-table",
    category: "table",
    furnitureName: "Couchtisch",
    lengthCm: 120,
    widthCm: 60,
    heightCm: 45,
    standardRooms: ["Wohnzimmer"],
    rooms: ["Wohnzimmer"],
  },
  {
    id: "tv-lowboard",
    category: "cabinet",
    furnitureName: "TV-Lowboard",
    lengthCm: 160,
    widthCm: 45,
    heightCm: 55,
    standardRooms: ["Wohnzimmer"],
    rooms: ["Wohnzimmer"],
  },
  {
    id: "dining-table",
    category: "table",
    furnitureName: "Esstisch",
    lengthCm: 180,
    widthCm: 90,
    heightCm: 76,
    standardRooms: ["Wohnzimmer", "Küche"],
    rooms: ["Wohnzimmer", "Küche"],
  },
  {
    id: "chair",
    category: "seating",
    furnitureName: "Stuhl",
    lengthCm: 45,
    widthCm: 45,
    heightCm: 90,
    standardRooms: ["Wohnzimmer", "Küche"],
    rooms: ["Wohnzimmer", "Küche"],
  },
  {
    id: "fridge",
    category: "appliance",
    furnitureName: "Kühlschrank",
    lengthCm: 60,
    widthCm: 65,
    heightCm: 200,
    standardRooms: ["Küche"],
    rooms: ["Küche"],
  },
  {
    id: "kitchen-high-cabinet",
    category: "cabinet",
    furnitureName: "Küchenhochschrank",
    lengthCm: 60,
    widthCm: 60,
    heightCm: 200,
    standardRooms: ["Küche"],
    rooms: ["Küche"],
  },
  {
    id: "washing-machine",
    category: "appliance",
    furnitureName: "Waschmaschine",
    lengthCm: 60,
    widthCm: 60,
    heightCm: 85,
    standardRooms: ["Badezimmer", "Keller", "Gäste-Bad"],
    rooms: ["Badezimmer", "Keller", "Gäste-Bad"],
  },
  {
    id: "bathroom-cabinet",
    category: "cabinet",
    furnitureName: "Badezimmerschrank",
    lengthCm: 80,
    widthCm: 35,
    heightCm: 190,
    standardRooms: ["Badezimmer", "Gäste-Bad"],
    rooms: ["Badezimmer", "Gäste-Bad"],
  },
  {
    id: "shelf",
    category: "shelving",
    furnitureName: "Regal",
    lengthCm: 80,
    widthCm: 35,
    heightCm: 180,
    standardRooms: ["Wohnzimmer", "Keller", "Dachboden", "Garage"],
    rooms: ["Wohnzimmer", "Keller", "Dachboden", "Garage", "Kinderzimmer"],
  },
  {
    id: "freezer",
    category: "appliance",
    furnitureName: "Gefrierschrank",
    lengthCm: 70,
    widthCm: 70,
    heightCm: 180,
    standardRooms: ["Keller", "Garage"],
    rooms: ["Keller", "Garage"],
  },
  {
    id: "workbench",
    category: "workshop",
    furnitureName: "Werkbank",
    lengthCm: 150,
    widthCm: 70,
    heightCm: 90,
    standardRooms: ["Garage"],
    rooms: ["Garage"],
  },
  {
    id: "bicycle",
    category: "vehicle",
    furnitureName: "Fahrrad",
    lengthCm: 180,
    widthCm: 60,
    heightCm: 110,
    standardRooms: ["Keller", "Garage"],
    rooms: ["Keller", "Garage"],
  },
  {
    id: "moving-box-standard",
    category: "box",
    furnitureName: "Umzugskarton Standard",
    lengthCm: 60,
    widthCm: 40,
    heightCm: 40,
    standardRooms: ["Keller", "Dachboden", "Garage"],
    rooms: ["Keller", "Dachboden", "Garage", "Wohnzimmer", "Schlafzimmer", "Kinderzimmer", "Gästezimmer"],
  },
];
