// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { resolvePrismaDatabaseUrls } from "./src/lib/prisma-database-url";

const rawDatabaseUrl =
  process.env["DATABASE_URL"] ||
  process.env["PRISMA_DATABASE_URL"] ||
  process.env["POSTGRES_URL"] ||
  process.env["POSTGRESQL_URL"] ||
  "";
const resolvedDatabaseUrls = resolvePrismaDatabaseUrls(rawDatabaseUrl);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolvedDatabaseUrls?.databaseUrl || rawDatabaseUrl,
    shadowDatabaseUrl: resolvedDatabaseUrls?.shadowDatabaseUrl,
  },
});
