// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { resolvePrismaDatabaseUrls } from "./src/lib/prisma-database-url";

const resolvedDatabaseUrls = resolvePrismaDatabaseUrls(process.env["DATABASE_URL"]);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolvedDatabaseUrls?.databaseUrl ?? process.env["DATABASE_URL"],
    shadowDatabaseUrl: resolvedDatabaseUrls?.shadowDatabaseUrl,
  },
});
